Fix unet download based on new folder structure
The U-Net is now stored in a subdirectory of the repo [here](https://huggingface.co/Lykon/dreamshaper-8/tree/main/unet). This change ensures that the UNet is downloaded from the right place.

Without this change, the code errors when running `python3 gradio_dmd.py` with the error message:

```
OSError: Lykon/dreamshaper-8 does not appear to have a file named config.json.
```

because there's no config.json in the root directory (anymore)